app = "${PROJECT_NAME}"

[build]
dockerfile = "Dockerfile"

# Dockerfile build args
[build.args]
BUILD_DATE = "${BUILD_DATE}"
CODE_RELEASE = "${CODE_SERVER_VERSION}"
DEFAULT_WORKSPACE = "${DEFAULT_WORKSPACE}"
SERVER_PORT = "${SERVER_PORT}"
INSTALL_NODE_FROM_NODESOURCE = "${INSTALL_NODE_FROM_NODESOURCE}"
NODE_MAJOR = "${NODE_MAJOR}"
USER_NAME = "${USER_NAME}"
USER_SHELL = "${USER_SHELL}"
INSTALL_CONTAINER_STRUCTURE_TEST = "${INSTALL_CONTAINER_STRUCTURE_TEST}"
CONTAINER_STRUCTURE_TEST_VERSION = "${CONTAINER_STRUCTURE_TEST_VERSION}"
INSTALL_HADOLINT = "${INSTALL_HADOLINT}"
HADOLINT_VERSION = "${HADOLINT_VERSION}"

# Runtime env, only available in entrypoint and beyond
[env]
TZ = "${TZ}"
DEFAULT_WORKSPACE = "${DEFAULT_WORKSPACE}"
PORT = "${SERVER_PORT}"
HOME = "${DEFAULT_WORKSPACE}"
GIT_USER = "${GIT_USER}"
GIT_EMAIL = "${GIT_EMAIL}"
USER_NAME = "${USER_NAME}"

[http_service]
internal_port = $SERVER_PORT # do not quote
force_https = true
auto_stop_machines = "${AUTO_STOP_MACHINE}"
auto_start_machines = true

[http_service.http_options]
idle_timeout = $IDLE_TIMEOUT # do not quote, max is 900

[[mounts]]
source = "code_workspace"
destination = "${DEFAULT_WORKSPACE}"
initial_size = "${INITIAL_DISK_SIZE}"

[[vm]]
size = "${VM_SIZE}"
memory = "${VM_MEMORY}"
